name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main

jobs:
  code-check:
    if: github.event.pull_request.draft == false
    {% if cookiecutter.open_source == 'y' -%}
    runs-on: ubuntu-latest
    {% else -%}
  runs-on: [self-hosted, self-hosted-ubuntu-latest]
    {% endif -%}
    steps:
      - uses: actions/checkout@v{{ cookiecutter._checkout_action_version }}
      - uses: actions/setup-python@v{{ cookiecutter._setup_python_action_version }}
        with:
          python-version: "{{ cookiecutter.python_version }}"
      - uses: pre-commit/action@v{{ cookiecutter._pre_commit_action_version }}

  pytest:
    if: github.event.pull_request.draft == false
    strategy:
        matrix:
            {% if cookiecutter.open_source == 'y' -%}
            os: [windows-latest, macos-latest, ubuntu-latest]
            {% else -%}
            os: [self-hosted-ubuntu-latest]
            {% endif -%}
            python-version: ["{{ cookiecutter.python_version }}"]
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    steps:
      - uses: actions/checkout@v{{ cookiecutter._checkout_action_version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v{{ cookiecutter._setup_uv_action_version }}
        with:
          enable-cache: true
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}

      - name: Install Dependencies
        run: uv sync --all-extras

      - name: Test with pytest
        run: uv run --no-cache pytest
