name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main

concurrency:
  group: {% raw %}${{ github.workflow }}-${{ github.head_ref }}{% endraw %}
  cancel-in-progress: true

jobs:
  code-check:
    if: github.event.pull_request.draft == false
    permissions:
      contents: read
      pull-requests: write
    {% if cookiecutter.open_source == 'y' -%}
    runs-on: ubuntu-latest
    {% else -%}
  runs-on: [self-hosted, self-hosted-ubuntu-latest]
    {% endif -%}
    steps:
      - uses: actions/checkout@v{{ cookiecutter._checkout_action_version }}
        with:
          persist-credentials: false
          ref: main

      - name: Install uv and set up Python
        uses: astral-sh/setup-uv@v{{ cookiecutter._setup_uv_action_version }}
        with:
          enable-cache: false
          python-version: "{{ cookiecutter.python_version }}"

      - run: python -m pip install pre-commit
        shell: bash

      - run: pre-commit run --show-diff-on-failure --color=always --all-files
        shell: bash

  pytest:
    if: github.event.pull_request.draft == false
    permissions:
      contents: read
      pull-requests: write
    strategy:
        matrix:
            {% if cookiecutter.open_source == 'y' -%}
            os: [windows-latest, macos-latest, ubuntu-latest]
            {% else -%}
            os: [self-hosted-ubuntu-latest]
            {% endif -%}
            python-version: ["{{ cookiecutter.python_version }}"]
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    steps:
      - uses: actions/checkout@v{{ cookiecutter._checkout_action_version }}
        with:
          persist-credentials: false
          ref: main

      - name: Install uv and set up Python
        uses: astral-sh/setup-uv@v{{ cookiecutter._setup_uv_action_version }}
        with:
          enable-cache: false
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}

      - name: Install Dependencies
        run: uv sync --all-extras

      - name: Test with pytest
        run: uv run --no-cache pytest
